{
 "title": "esp-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PV",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "battery = from(bucket: \"solaredge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"battery\")\n  |> filter(fn: (r) => r[\"_field\"] == \"instantaneous_power\")\n\ninverter = from(bucket: \"solaredge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power_ac\")\n\njoin(tables: {battery: battery, inverter: inverter}, on: [\"_time\", \"_start\", \"_stop\"], method: \"inner\")\n  |> map(fn: (r) => ({_time: r._time, _value: r._value_inverter + r._value_battery }))\n  |> aggregateWindow(every: 2m, fn: median, createEmpty: false)\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Verbrauch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "meter = from(bucket: \"solaredge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"meter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n\ninverter = from(bucket: \"solaredge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power_ac\")\n\njoin(tables: {meter: meter, inverter: inverter}, on: [\"_time\", \"_start\", \"_stop\"], method: \"inner\")\n  |> map(fn: (r) => ({_time: r._time, _value: r._value_inverter - r._value_meter }))\n  |> aggregateWindow(every: 2m, fn: median, createEmpty: false)\n  |> last()"
    }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"weather-forecast\")\n  |> range(start: v.timeRangeStop, stop: date.add(d: 48h, to: v.timeRangeStop))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WeatherForecast\")\n  |> filter(fn: (r) => r[\"_field\"] == \"air_temperature\")\n  |> map(fn: (r) => ({_time: r._time, _value: r._value }))\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Charge",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solaredge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"battery\")\n  |> filter(fn: (r) => r[\"_field\"] == \"instantaneous_power\")\n  |> aggregateWindow(every: 2m, fn: median, createEmpty: false)\n  |> last()"
    }
   ]
  },
  {
   "title": "Inverter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solaredge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power_ac\")\n  |> aggregateWindow(every: 2m, fn: median, createEmpty: false)\n  |> last()"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solaredge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"battery\")\n  |> filter(fn: (r) => r[\"_field\"] == \"soe\")\n  |> aggregateWindow(every: 2m, fn: median, createEmpty: false)\n  |> last()"
    }
   ]
  },
  {
   "title": "Exp/Imp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solaredge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"meter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n  |> aggregateWindow(every: 2m, fn: median, createEmpty: false)\n  |> last()"
    }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mm/h" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"weather-forecast\")\n  |> range(start: v.timeRangeStop, stop: date.add(d: 48h, to: v.timeRangeStop))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WeatherForecast\")\n  |> filter(fn: (r) => r[\"_field\"] == \"precipitation_amount\")\n  |> map(fn: (r) => ({_time: r._time, _value: r._value }))\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Warmwasser",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodered\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> filter(fn: (r) => r[\"identity\"] == \"zigbee2mqtt/Heizung-Warmwasser\")\n  |> aggregateWindow(every: 2m, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temp. OG",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodered\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"identity\"] == \"zigbee2mqtt/Temperatur-OG\")\n  |> aggregateWindow(every: 2m, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}